import { EventRequest, InventoryItem, ScheduleProps } from "@/components/type";

export const schedules: ScheduleProps[] = [
	{
		day: "Monday",
		events: [
			{
				title: "Team Meeting",
				time: "9:00 AM - 10:00 AM",
				note: "Bring your own device",
				contact: "team@example.com",
				category: "Meeting",
				status: "Approved",
				description:
					"Weekly sync-up with the team to discuss project updates and tasks.",
				pic: "Alice Johnson",
			},
			{
				title: "Design Review",
				time: "10:30 AM - 11:30 AM",
				note: "",
				contact: "design@example.com",
				category: "Research",
				status: "Pending",
				description: "Reviewing the latest design mockups with the UI/UX team.",
				pic: "Brian Lee",
			},
		],
	},
	{
		day: "Tuesday",
		events: [
			{
				title: "Client Presentation",
				time: "10:00 AM - 11:00 AM",
				note: "",
				contact: "client@example.com",
				category: "Presentation",
				status: "Pending",
				description:
					"Presenting the project proposal to the client and gathering feedback.",
				pic: "Cynthia Smith",
			},
			{
				title: "QA Testing",
				time: "2:00 PM - 3:00 PM",
				note: "",
				contact: "qa@example.com",
				category: "Testing",
				status: "Pending",
				description: "Testing new features and logging bugs.",
				pic: "David Kim",
			},
		],
	},
	{
		day: "Wednesday",
		events: [
			{
				title: "Workshop on UX Design",
				time: "11:00 AM - 12:00 PM",
				note: "",
				contact: "ux@example.com",
				category: "Workshop",
				status: "Pending",
				description:
					"An interactive workshop focusing on the principles of user experience design.",
				pic: "Emma Williams",
			},
		],
	},
	{
		day: "Thursday",
		events: [
			{
				title: "Sprint Planning",
				time: "1:00 PM - 2:00 PM",
				note: "",
				contact: "scrum@example.com",
				category: "Planning",
				status: "Pending",
				description: "Planning the next sprint and assigning tasks.",
				pic: "Frank Miller",
			},
		],
	},
	{
		day: "Friday",
		events: [
			{
				title: "Code Review",
				time: "2:00 PM - 3:00 PM",
				note: "",
				contact: "dev@example.com",
				category: "Review",
				status: "Pending",
				description: "Reviewing code submissions and providing feedback.",
				pic: "Grace Chen",
			},
			{
				title: "Retrospective",
				time: "4:00 PM - 5:00 PM",
				note: "",
				contact: "scrum@example.com",
				category: "Meeting",
				status: "Pending",
				description: "Discussing what went well and what can be improved.",
				pic: "Henry Brown",
			},
		],
	},
];

export const inventoryItem: InventoryItem[] = [
	{
		id: "1",
		nameItem: "Laptop Dell XPS 13",
		procurementYear: 2021,
		specification: "Intel i7, 16GB RAM, 512GB SSD",
		quantity: 10,
		goodCondition: 8,
		fairCondition: 1,
		poorCondition: 1,
		note: "Used for development and testing",
	},
	{
		id: "2",
		nameItem: "Projector Epson X500",
		procurementYear: 2020,
		specification: "Full HD, 3000 lumens",
		quantity: 5,
		goodCondition: 4,
		fairCondition: 1,
		poorCondition: 0,
		note: "Used for presentations and meetings",
	},
	{
		id: "3",
		nameItem: "HP LaserJet Pro M404dn",
		procurementYear: 2019,
		specification: "Monochrome, Duplex Printing",
		quantity: 3,
		goodCondition: 2,
		fairCondition: 1,
		poorCondition: 0,
		note: "Shared office printer",
	},
	{
		id: "4",
		nameItem: "Apple MacBook Pro 16",
		procurementYear: 2022,
		specification: "M1 Pro, 32GB RAM, 1TB SSD",
		quantity: 6,
		goodCondition: 6,
		fairCondition: 0,
		poorCondition: 0,
		note: "For design and video editing",
	},
	{
		id: "5",
		nameItem: "Samsung Flip 2 Whiteboard",
		procurementYear: 2021,
		specification: "65-inch, Touchscreen",
		quantity: 2,
		goodCondition: 2,
		fairCondition: 0,
		poorCondition: 0,
		note: "Interactive meetings",
	},
	{
		id: "6",
		nameItem: "Cisco Webex Room Kit",
		procurementYear: 2020,
		specification: "Video conferencing system",
		quantity: 4,
		goodCondition: 3,
		fairCondition: 1,
		poorCondition: 0,
		note: "Conference rooms",
	},
	{
		id: "7",
		nameItem: "Lenovo ThinkPad X1 Carbon",
		procurementYear: 2021,
		specification: "Intel i5, 16GB RAM, 256GB SSD",
		quantity: 8,
		goodCondition: 7,
		fairCondition: 1,
		poorCondition: 0,
		note: "Business laptops",
	},
	{
		id: "8",
		nameItem: "Canon EOS 90D Camera",
		procurementYear: 2019,
		specification: "32.5MP, 4K Video",
		quantity: 2,
		goodCondition: 2,
		fairCondition: 0,
		poorCondition: 0,
		note: "Media and documentation",
	},
	{
		id: "9",
		nameItem: "Microsoft Surface Pro 7",
		procurementYear: 2020,
		specification: "Intel i5, 8GB RAM, 128GB SSD",
		quantity: 5,
		goodCondition: 4,
		fairCondition: 1,
		poorCondition: 0,
		note: "Portable workstations",
	},
	{
		id: "10",
		nameItem: "APC Smart-UPS 1500VA",
		procurementYear: 2018,
		specification: "Uninterruptible Power Supply",
		quantity: 3,
		goodCondition: 2,
		fairCondition: 1,
		poorCondition: 0,
		note: "Backup power for servers",
	},
	{
		id: "11",
		nameItem: "Dell UltraSharp U2720Q",
		procurementYear: 2021,
		specification: "27-inch 4K Monitor",
		quantity: 7,
		goodCondition: 7,
		fairCondition: 0,
		poorCondition: 0,
		note: "Design and development",
	},
	{
		id: "12",
		nameItem: "Logitech Rally Camera",
		procurementYear: 2020,
		specification: "PTZ, 4K Ultra-HD",
		quantity: 2,
		goodCondition: 2,
		fairCondition: 0,
		poorCondition: 0,
		note: "Video conferencing",
	},
	{
		id: "13",
		nameItem: "Brother HL-L2350DW Printer",
		procurementYear: 2019,
		specification: "Monochrome, Wireless",
		quantity: 4,
		goodCondition: 3,
		fairCondition: 1,
		poorCondition: 0,
		note: "Departmental printer",
	},
	{
		id: "14",
		nameItem: "BenQ GW2780 Monitor",
		procurementYear: 2020,
		specification: "27-inch, Full HD",
		quantity: 6,
		goodCondition: 5,
		fairCondition: 1,
		poorCondition: 0,
		note: "General use",
	},
	{
		id: "15",
		nameItem: "Jabra Speak 710 Speakerphone",
		procurementYear: 2021,
		specification: "Bluetooth, USB",
		quantity: 3,
		goodCondition: 3,
		fairCondition: 0,
		poorCondition: 0,
		note: "Meetings and calls",
	},
	{
		id: "16",
		nameItem: "Synology DS920+ NAS",
		procurementYear: 2022,
		specification: "4-bay, 32TB max",
		quantity: 2,
		goodCondition: 2,
		fairCondition: 0,
		poorCondition: 0,
		note: "File storage",
	},
	{
		id: "17",
		nameItem: "Epson EcoTank L3150",
		procurementYear: 2020,
		specification: "Color, Wi-Fi",
		quantity: 3,
		goodCondition: 2,
		fairCondition: 1,
		poorCondition: 0,
		note: "Office printing",
	},
	{
		id: "18",
		nameItem: "TP-Link Archer AX6000 Router",
		procurementYear: 2021,
		specification: "Wi-Fi 6, 8 LAN Ports",
		quantity: 2,
		goodCondition: 2,
		fairCondition: 0,
		poorCondition: 0,
		note: "Network backbone",
	},
	{
		id: "19",
		nameItem: "Sony WH-1000XM4 Headphones",
		procurementYear: 2022,
		specification: "Noise Cancelling, Wireless",
		quantity: 5,
		goodCondition: 5,
		fairCondition: 0,
		poorCondition: 0,
		note: "Remote work",
	},
	{
		id: "20",
		nameItem: "Wacom Intuos Pro Tablet",
		procurementYear: 2021,
		specification: "Medium, Bluetooth",
		quantity: 2,
		goodCondition: 2,
		fairCondition: 0,
		poorCondition: 0,
		note: "Digital illustration",
	},
];

export const eventRequestItem: EventRequest[] = [
	{
		id: "2",
		date: "2024-06-10",
		title: "Project Kickoff Meeting",
		time: "09:00 AM - 10:00 AM",
		description: "Kickoff meeting for the new project.",
		pic: "John Doe",
		note: "Important stakeholders invited.",
		contact: "john.doe@example.com",
		category: "kelas",
		status: "Approved",
	},
	{
		id: "3",
		date: "2024-06-11",
		title: "Design Sprint",
		time: "10:00 AM - 12:00 PM",
		description: "Collaborative design sprint for new features.",
		pic: "Design Team",
		note: "Bring sketches and ideas.",
		contact: "design.team@example.com",
		category: "praktikum",
		status: "Cancelled",
	},
	{
		id: "4",
		date: "2024-06-12",
		title: "Client Feedback Session",
		time: "02:00 PM - 03:00 PM",
		description: "Session to gather feedback from the client.",
		pic: "Client",
		note: "Prepare demo materials.",
		contact: "client@example.com",
		category: "skripsi",
		status: "Pending",
	},
	{
		id: "5",
		date: "2024-06-13",
		title: "QA Review",
		time: "11:00 AM - 12:00 PM",
		description: "Quality assurance review for the latest release.",
		pic: "QA Team",
		note: "",
		contact: "qa@example.com",
		category: "praktikum",
		status: "Cancelled",
	},
	{
		id: "6",
		date: "2024-06-14",
		title: "Weekly Standup",
		time: "09:30 AM - 10:00 AM",
		description: "Weekly team standup meeting.",
		pic: "Team Lead",
		note: "",
		contact: "teamlead@example.com",
		category: "kelas",
		status: "Approved",
	},
	{
		id: "7",
		date: "2024-06-15",
		title: "Retrospective",
		time: "04:00 PM - 05:00 PM",
		description: "Sprint retrospective meeting.",
		pic: "Scrum Master",
		note: "",
		contact: "scrum.master@example.com",
		category: "kelas",
		status: "Pending",
	},
	{
		id: "8",
		date: "2024-06-16",
		title: "Infrastructure Upgrade",
		time: "01:00 PM - 03:00 PM",
		description: "Upgrading server infrastructure.",
		pic: "IT Team",
		note: "Downtime expected.",
		contact: "it@example.com",
		category: "lainnya",
		status: "Pending",
	},
	{
		id: "9",
		date: "2024-06-17",
		title: "Marketing Strategy Meeting",
		time: "10:00 AM - 11:30 AM",
		description: "Discussing new marketing strategies.",
		pic: "Marketing Team",
		note: "",
		contact: "marketing@example.com",
		category: "kelas",
		status: "Pending",
	},
	{
		id: "10",
		date: "2024-06-18",
		title: "Product Demo",
		time: "03:00 PM - 04:00 PM",
		description: "Demonstration of the new product features.",
		pic: "Product Team",
		note: "",
		contact: "product@example.com",
		category: "lainnya",
		status: "Approved",
	},
	{
		id: "11",
		date: "2024-06-19",
		title: "Security Audit",
		time: "11:00 AM - 01:00 PM",
		description: "Comprehensive security audit.",
		pic: "Security Team",
		note: "All teams must participate.",
		contact: "security@example.com",
		category: "lainnya",
		status: "Pending",
	},
	{
		id: "12",
		date: "2024-06-20",
		title: "Team Building Activity",
		time: "02:00 PM - 05:00 PM",
		description: "Outdoor team building exercises.",
		pic: "HR Team",
		note: "Wear comfortable clothes.",
		contact: "hr@example.com",
		category: "lainnya",
		status: "Pending",
	},
	{
		id: "13",
		date: "2024-06-21",
		title: "Board Meeting",
		time: "09:00 AM - 11:00 AM",
		description: "Quarterly board meeting.",
		pic: "Board Members",
		note: "Board members only.",
		contact: "board@example.com",
		category: "kelas",
		status: "Approved",
	},
	{
		id: "14",
		date: "2024-06-22",
		title: "System Backup",
		time: "12:00 AM - 02:00 AM",
		description: "Scheduled system backup.",
		pic: "IT Team",
		note: "No access during this time.",
		contact: "it@example.com",
		category: "lainnya",
		status: "Pending",
	},
	{
		id: "15",
		date: "2024-06-23",
		title: "Training Session",
		time: "10:00 AM - 12:00 PM",
		description: "Training on new software tools.",
		pic: "Trainer",
		note: "",
		contact: "training@example.com",
		category: "praktikum",
		status: "Pending",
	},
	{
		id: "16",
		date: "2024-06-24",
		title: "Vendor Meeting",
		time: "03:00 PM - 04:00 PM",
		description: "Meeting with hardware vendors.",
		pic: "Procurement Team",
		note: "",
		contact: "procurement@example.com",
		category: "kelas",
		status: "Pending",
	},
	{
		id: "17",
		date: "2024-06-25",
		title: "App Launch",
		time: "01:00 PM - 02:00 PM",
		description: "Official launch of the new app.",
		pic: "Launch Team",
		note: "Invite all stakeholders.",
		contact: "launch@example.com",
		category: "lainnya",
		status: "Approved",
	},
	{
		id: "18",
		date: "2024-06-26",
		title: "Bug Bash",
		time: "11:00 AM - 01:00 PM",
		description: "Team-wide bug fixing session.",
		pic: "QA Team",
		note: "",
		contact: "qa@example.com",
		category: "praktikum",
		status: "Pending",
	},
	{
		id: "19",
		date: "2024-06-27",
		title: "Customer Support Review",
		time: "02:00 PM - 03:00 PM",
		description: "Review of customer support tickets.",
		pic: "Support Team",
		note: "",
		contact: "support@example.com",
		category: "lainnya",
		status: "Pending",
	},
	{
		id: "20",
		date: "2024-06-28",
		title: "Annual General Meeting",
		time: "09:00 AM - 12:00 PM",
		description: "Company-wide annual meeting.",
		pic: "Admin Team",
		note: "All employees must attend.",
		contact: "admin@example.com",
		category: "kelas",
		status: "Approved",
	},
];
